### GET /api/blogs
http://localhost:3003/api/blogs

### POST /api/blogs
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Hello FullstackOpen",
  "author": "Pacis Baron",
  "url": "https://example.com",
  "likes": 7
}

### POST 
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "nghha",
  "name": "haf mong mer",
  "password": "2812nghh@"
}
### 
GET http://localhost:3003/api/users